---

instance_groups:
  - name: concourse
    jobs:
      - name: atc
        properties:
          github_auth:
            client_id: (( grab $GITHUB_CLIENT_ID ))
            client_secret: (( grab $GITHUB_CLIENT_SECRET ))
          main_team:
            auth:
              github:
                users:
                - 46bit
                - alext
                - bandesz
                - chrisfarms
                - keymon
                - LeePorte
                - paroxp
                - richardTowers
                - samcrang
