
---

instance_groups:
  - name: concourse
    jobs:
      - name: web
        properties:
          main_team:
            auth:
              github:
                users:
                  - (( append ))
                  - kr8n3r
                  - poveyd
                  - barsutka
                  - szd55gds
                  - philandstuff
                  - Krenair
                  - chrisfarms
                  - cbaines
