
---

instance_groups:
  - name: concourse
    jobs:
      - name: atc
        properties:
          main_team:
            auth:
              github:
                users:
                  - (( append ))
                  - jpluscplusm
                  - venusbb
