AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'scripts/vendor/**/*'
    - 'concourse/spec/**/*'
  TargetRubyVersion: 2.5
Performance/HashEachMethods:
  Enabled: false
Performance/RegexpMatch:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
