AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'scripts/vendor/**/*'
  TargetRubyVersion: 2.5
Metrics/BlockLength:
  # FIXME: Remove when upstream PR is released:
  # https://github.com/alphagov/govuk-lint/pull/87
  Enabled: true
  Exclude:
    - "**/spec/**/*"
Performance/HashEachMethods:
  Enabled: false
Performance/RegexpMatch:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
