inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'scripts/vendor/**/*'
    - 'concourse/spec/**/*'

RSpec/DescribedClass:
    Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
