dist: focal
sudo: false
rvm:
  - 2.7
env:
  global:
    - TF_VERSION="0.11.14"
    - SPRUCE_VERSION="1.24.1"
    - BOSH_CLI_VERSION="6.1.1"
    - CERTSTRAP_VERSION="1.2.0"
    - SHELLCHECK_VERSION="0.7.0"
    - GO_VERSION="1.14"

addons:
  apt:
    sources:
      - git-core
    packages:
      - git
      - gnupg
      - xz-utils

before_install:
  - |
    mkdir ~/bin
    export PATH=~/bin:$PATH
  - |
    echo "Fetching shellcheck"
    wget -qO- "https://github.com/koalaman/shellcheck/releases/download/v${SHELLCHECK_VERSION}/shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz" | tar -xJv
    cp "shellcheck-v${SHELLCHECK_VERSION}/shellcheck" ~/bin
  - |
    echo "Fetching Terraform"
    set -e
    wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
    unzip -o terraform_${TF_VERSION}_linux_amd64.zip -d ~/bin
    rm terraform_${TF_VERSION}_linux_amd64.zip
  - |
    echo "Fetching Spruce"
    set -e
    wget https://github.com/geofffranks/spruce/releases/download/v${SPRUCE_VERSION}/spruce-linux-amd64
    mv spruce-linux-amd64 ~/bin/spruce && chmod +x ~/bin/spruce
  - |
    echo "Fetching certstrap"
    set -e
    wget https://github.com/square/certstrap/releases/download/v${CERTSTRAP_VERSION}/certstrap-${CERTSTRAP_VERSION}-linux-amd64
    mv certstrap-${CERTSTRAP_VERSION}-linux-amd64 ~/bin/certstrap && chmod +x ~/bin/certstrap
  - |
    echo "Fetching bosh cli"
    set -e
    wget https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-${BOSH_CLI_VERSION}-linux-amd64
    mv bosh-cli-${BOSH_CLI_VERSION}-linux-amd64 ~/bin/bosh && chmod +x ~/bin/bosh
  - pip install --user yamllint

  - 'eval "$(gimme "$GO_VERSION")"'
  - export GOPATH=$HOME/gopath
  - export PATH=$HOME/gopath/bin:$PATH
  - go get -u github.com/alphagov/paas-cf/tools/pipecleaner
  - bundle install

script:
  - make test
