version: '3'

services:
  concourse-db:
    image: postgres
    environment:
    - POSTGRES_DB=${CONCOURSE_POSTGRES_DATABASE:-concourse}
    - POSTGRES_PASSWORD=${CONCOURSE_POSTGRES_PASSWORD:-concourse_pass}
    - POSTGRES_USER=${CONCOURSE_POSTGRES_USER:-concourse_user}
    - PGDATA=/database

  concourse:
    image: concourse/concourse:5.1.0
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    environment:
    - CONCOURSE_POSTGRES_HOST=${CONCOURSE_POSTGRES_HOST:-concourse-db}
    - CONCOURSE_POSTGRES_USER=${CONCOURSE_POSTGRES_USER:-concourse_user}
    - CONCOURSE_POSTGRES_PASSWORD=${CONCOURSE_POSTGRES_PASSWORD:-concourse_pass}
    - CONCOURSE_POSTGRES_DATABASE=${CONCOURSE_POSTGRES_DATABASE:-concourse}
    - CONCOURSE_EXTERNAL_URL
    - CONCOURSE_ADD_LOCAL_USER=${CONCOURSE_ADD_LOCAL_USER:-test:test}
    - CONCOURSE_MAIN_TEAM_LOCAL_USER=${CONCOURSE_ATC_USER:-test}
    - CONCOURSE_WORKER_TSA_WORKER_PRIVATE_KEY=a
    - CONCOURSE_WORKER_WORK_DIR=/tmp
