---
jobs:
- name: bosh
  templates:
  - {name: datadog-agent, release: datadog-agent}
  properties:
    datadog: (( inject meta.datadog ))
    tags:
      bosh-job: bosh
      bosh-az: (( grab terraform_outputs.bosh_az_label ))
