concourse-db:
  image: postgres:9.6.2-alpine
  restart: always
  environment:
    POSTGRES_DB: "${CONCOURSE_DATABASE_NAME}"
    POSTGRES_USER: "${CONCOURSE_DATABASE_USER}"
    POSTGRES_PASSWORD: "${CONCOURSE_DATABASE_PASS}"
    PGDATA: /database

concourse-web:
  image: concourse/concourse:2.7.0
  links: [concourse-db]
  command: web
  restart: always
  ports: ["8080:8080"]
  volumes: ["./keys/web:/concourse-keys"]
  environment:
    CONCOURSE_BASIC_AUTH_USERNAME: "${CONCOURSE_ATC_USER}"
    CONCOURSE_BASIC_AUTH_PASSWORD: "${CONCOURSE_ATC_PASSWORD}"
    CONCOURSE_EXTERNAL_URL: "${CONCOURSE_URL}"
    CONCOURSE_POSTGRES_DATA_SOURCE: |-
      postgres://${CONCOURSE_DATABASE_USER}:${CONCOURSE_DATABASE_PASS}@concourse-db:5432/${CONCOURSE_DATABASE_NAME}?sslmode=disable

concourse-worker:
  image: concourse/concourse:2.7.0
  privileged: true
  links: [concourse-web]
  command: worker
  restart: always
  volumes: ["./keys/worker:/concourse-keys"]
  environment:
    CONCOURSE_TSA_HOST: concourse-web

