releases:
  - name: riemann
    url: https://github.com/alphagov/paas-riemann-boshrelease/releases/download/v0.5.0-dev/riemann-gds-4.tgz
    sha1: 76bbc59dfb46052353226839c67ad1f011ed2225
    version: gds-4

jobs:
  - name: concourse
    templates:
      - name: riemann
        release: riemann
        properties:
          riemann:
            datadog:
              api_key: (( grab meta.datadog.api_key ))

      - name: atc
        properties:
          riemann:
            host: '127.0.0.1'
            service_prefix: 'concourse.'
            tags:
              aws_account: (( grab $AWS_ACCOUNT ))
              deploy_env: (( grab terraform_outputs.environment ))
