---
releases:
  - name: collectd
    version: 0.1.2
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/collectd-0.1.2.tgz
    sha1: e269c89a4a65c1464eb9a5a56152a9028acfc1dd

meta:
  collectd:
    interval: 10
    config: |
      WriteQueueLimitHigh 100000
      LoadPlugin cpu
      LoadPlugin disk
      LoadPlugin entropy
      LoadPlugin load
      LoadPlugin memory
      LoadPlugin swap
      LoadPlugin uptime

      LoadPlugin interface
      <Plugin interface>
        IgnoredSelected false
        Interface lo0
        Interface eth0
      </Plugin>

      LoadPlugin df
      <Plugin df>
        FSType "tracefs"
        IgnoreSelected true
        ReportInodes true
        ReportReserved true
      </Plugin>

      LoadPlugin syslog
      <Plugin syslog>
        LogLevel warning
        NotifyLevel WARNING
      </Plugin>

      LoadPlugin vmem
      <Plugin vmem>
        Verbose false
      </Plugin>

      LoadPlugin "write_graphite"
      <Plugin "write_graphite">
       <Node "myNode">
         #FIXME: hard coded static IP to be removed during #121602315
         # This address comes from 040-graphite.yml:31 in the CloudFoundry
         # manifest and has been copied as `grab` cannot interpolate in a
         # multi-line string.
         Host "10.0.16.20"
         Port "2003"
         Prefix "collectd."
         EscapeCharacter "_"
         SeparateInstances true
         AlwaysAppendDS false
       </Node>
      </Plugin>
