---
releases:
  - name: os-conf
    version: commit-3c5609485a57b1314a0114b1e4157e6426fbf14a

addons:
  - name: os-configuration
    jobs:
    - name: set_mtu
      release: os-conf
  - name: collectd
    jobs:
    - name: collectd
      release: collectd
    properties:
      collectd: (( grab meta.collectd ))
  - name: syslog_forwarder
    jobs:
    - name: syslog_forwarder
      release: syslog
    properties:
      syslog:
        address: (( grab terraform_outputs.logsearch_ingestor_elb_dns_name ))
        port: 2514
        transport: 'relp'
        log_template: 'metron_agent'
  - name: syslog_cleanup
    jobs:
    - name: cleanup_syslog_forwarding
      release: os-conf
      properties:
        syslog_daemon_config: # Note: property also used by metron_agent in main manifest
          enable: false
