---
addons:
  - name: collectd
    jobs:
    - name: collectd
      release: collectd
    properties:
      collectd: (( grab meta.collectd ))
  - name: syslog_forwarder
    jobs:
    - name: syslog_forwarder
      release: syslog
    properties:
      syslog:
        address: (( grab terraform_outputs.logsearch_ingestor_elb_dns_name ))
        port: 5514
        transport: 'tcp'
        log_template: 'metron_agent'
