dns_api_client_tls: ((dns_api_client_tls))
dns_api_server_tls: ((dns_api_server_tls))
dns_api_tls_ca: ((dns_api_tls_ca))
dns_api_tls_ca_old: ((dns_api_tls_ca_old))
dns_healthcheck_client_tls: ((dns_healthcheck_client_tls))
dns_healthcheck_server_tls: ((dns_healthcheck_server_tls))
dns_healthcheck_tls_ca: ((dns_healthcheck_tls_ca))
dns_healthcheck_tls_ca_old: ((dns_healthcheck_tls_ca_old))

# These variable definitions, from which our *_ca_old additions derive, are
# borrowed from upstream [1]. We don't comsume bosh-deployment as an upstream
# (yet), hence we're embedding them here.
# [1] https://github.com/cloudfoundry/bosh-deployment/blob/master/runtime-configs/dns.yml

variables:

## Upstream 

- name: dns_healthcheck_tls_ca
  type: certificate
  options:
    is_ca: true
    common_name: dns-healthcheck-tls-ca

- name: dns_healthcheck_server_tls
  type: certificate
  options:
    ca: dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - server_auth

- name: dns_healthcheck_client_tls
  type: certificate
  options:
    ca: dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - client_auth

- name: dns_api_tls_ca
  type: certificate
  options:
    is_ca: true
    common_name: dns-api-tls-ca

- name: dns_api_server_tls
  type: certificate
  options:
    ca: dns_api_tls_ca
    common_name: api.bosh-dns
    extended_key_usage:
    - server_auth

- name: dns_api_client_tls
  type: certificate
  options:
    ca: dns_api_tls_ca
    common_name: api.bosh-dns
    extended_key_usage:
    - client_auth

## Our additions

- name: dns_healthcheck_tls_ca_old
  type: certificate
  options:
    is_ca: true
    common_name: dns-healthcheck-tls-ca

- name: dns_api_tls_ca_old
  type: certificate
  options:
    is_ca: true
    common_name: dns-api-tls-ca
