---
meta:
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: "3586.42"

  zone: (( grab terraform_outputs.zone0 ))

name: concourse

releases:
  - name: concourse
    version: 4.1.0
    url: https://bosh.io/d/github.com/concourse/concourse?v=4.1.0
    sha1: 513e3a88d135e6e2cd8a974702e2e63caa0cb82b
  - name: garden-runc
    version: 1.16.3
    url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.16.3
    sha1: 2a7c813e7e4d862e19334addf022916fb6b91eb0
  - name: postgres
    version: 29
    url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=29
    sha1: 24d2e2887a45258b71bc40577c0f406180e47701

properties:
  aws:
    credentials_source: env_or_profile
    region: (( grab terraform_outputs.region ))

resource_pools:
  - name: concourse
    network: concourse
    stemcell:
      name: (( grab meta.stemcell.name ))
      version: (( grab meta.stemcell.version ))
    cloud_properties:
      instance_type: (( grab $CONCOURSE_INSTANCE_TYPE ))
      availability_zone: (( grab meta.zone ))
      iam_instance_profile: (( grab $CONCOURSE_INSTANCE_PROFILE ))
      elbs:
      - (( grab terraform_outputs.concourse_elb_name ))
      ephemeral_disk:
        size: 102400
        type: gp2
      key_name: (( grab terraform_outputs.concourse_key_pair_name ))
      security_groups:
      - (( grab terraform_outputs.bosh_managed_security_group ))
      - (( grab terraform_outputs.concourse_security_group ))
      - (( grab terraform_outputs.ssh_security_group ))
      - (( grab terraform_outputs.bosh_api_client_security_group ))
      - (( grab terraform_outputs.bosh_ssh_client_security_group ))
    env:
      bosh:
        password: (( grab secrets.concourse_vcap_password ))
        ipv6:
          enable: true

disk_pools:
  - name: db
    disk_size: 10240
    cloud_properties:
      type: gp2

networks:
  - name: concourse
    type: manual
    subnets:
      - range: 10.0.0.0/24
        dns: [10.0.0.2]
        gateway: 10.0.0.1
        reserved:
        - 10.0.0.0 - 10.0.0.9
        static:
        - 10.0.0.10 - 10.0.0.20

        cloud_properties:
          subnet: (( grab terraform_outputs.subnet0_id ))
  - name: public
    type: vip

instance_groups:
  - name: concourse
    instances: 1
    resource_pool: concourse
    persistent_disk_pool: db

    jobs:
      - name: postgres
        release: postgres
        properties:
          databases:
            port: 5432
            databases:
              - name: atc
            roles:
              - name: atc
                password: (( grab secrets.concourse_postgres_password ))

      - name: atc
        release: concourse
        properties:
          external_url: (( concat "https://" terraform_outputs.concourse_dns_name ))
          basic_auth_username: admin
          basic_auth_password: (( grab secrets.concourse_atc_password ))
          auth_duration: (( grab $CONCOURSE_AUTH_DURATION ))
          postgresql:
            database: atc
            role:
              name: atc
              password: (( grab secrets.concourse_postgres_password ))
          token_signing_key: (( grab secrets.concourse_token_signing_key ))

      - name: worker
        release: concourse
        properties:
          baggageclaim:
            url: "http://127.0.0.1:7788"
          tsa:
            host: 127.0.0.1
            port: 2222
            host_public_key: (( grab secrets.concourse_tsa_host_key.public_key ))
            worker_key: (( grab secrets.concourse_worker_key ))

      - name: tsa
        release: concourse
        properties:
          forward_host: 127.0.0.1
          atc:
            address: 127.0.0.1:8080
          host_key: (( grab secrets.concourse_tsa_host_key ))
          token_signing_key: (( grab secrets.concourse_token_signing_key ))
          authorized_keys: [(( grab secrets.concourse_worker_key.public_key ))]

      - name: baggageclaim
        release: concourse

      - name: garden
        release: garden-runc
        properties:
          garden:
            listen_network: tcp
            listen_address: 0.0.0.0:7777
            graph_cleanup_threshold_in_mb: 3072
            max_containers: 1024
            network_pool: "10.254.0.0/20"

            # Override concourse containers to use VPC DNS instead of bosh-dns
            # See https://github.com/concourse/concourse/issues/2482 for details
            dns_servers:
              - 10.0.0.2

    networks:
      - name: public
        static_ips:
        - (( grab terraform_outputs.concourse_elastic_ip ))
      - name: concourse
        static_ips: (( static_ips(0) ))
        default: [dns, gateway]

compilation:
  workers: 1
  network: concourse
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: c4.large
    availability_zone: (( grab meta.zone ))
    iam_instance_profile: compilation-vm
    auto_assign_public_ip: true

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
