---
meta:
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-xenial-go_agent
    version: "170.45"

  zone: (( grab terraform_outputs_zone0 ))

name: concourse

# These versions and checksums are taken from the versions.yml file from the
# relevant tag of https://github.com/concourse/concourse-bosh-deployment
releases:
  # TODO: Use the upstream build again after the following PR was released:
  # https://github.com/concourse/concourse/pull/2785
  # This version is 4.2.2 + the above change
  - name: concourse
    version: 0.1.3
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/concourse-0.1.3.tgz
    sha1: 77a0ce9f8e32a157bd40b4c4cd85325f9cc77a0c
  - name: garden-runc
    version: 1.18.2
    url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.18.2
    sha1: f761349dfe829fb2e17ab53eb058267209275038
  - name: postgres
    version: 30
    url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=30
    sha1: a798999d29b9f5aa12035cff907b26674b491200

properties:
  aws:
    credentials_source: env_or_profile
    region: (( grab terraform_outputs_region ))

resource_pools:
  - name: concourse
    network: concourse
    stemcell:
      name: (( grab meta.stemcell.name ))
      version: (( grab meta.stemcell.version ))
    cloud_properties:
      instance_type: (( grab $CONCOURSE_INSTANCE_TYPE ))
      availability_zone: (( grab meta.zone ))
      iam_instance_profile: (( grab $CONCOURSE_INSTANCE_PROFILE ))
      elbs:
      - (( grab terraform_outputs_concourse_elb_name ))
      ephemeral_disk:
        size: 102400
        type: gp2
      security_groups:
      - (( grab terraform_outputs_bosh_managed_security_group ))
      - (( grab terraform_outputs_concourse_security_group ))
      - (( grab terraform_outputs_ssh_security_group ))
      - (( grab terraform_outputs_bosh_api_client_security_group ))
      - (( grab terraform_outputs_bosh_ssh_client_security_group ))
    env:
      bosh:
        password: (( grab secrets.vcap_password ))
        ipv6:
          enable: true

disk_pools:
  - name: db
    disk_size: 10240
    cloud_properties:
      type: gp2

networks:
  - name: concourse
    type: manual
    subnets:
      - range: 10.0.0.0/24
        dns: [10.0.0.2]
        gateway: 10.0.0.1
        reserved:
        - 10.0.0.0 - 10.0.0.9
        static:
        - 10.0.0.10 - 10.0.0.20

        cloud_properties:
          subnet: (( grab terraform_outputs_subnet0_id ))
  - name: public
    type: vip

instance_groups:
  - name: concourse
    instances: 1
    resource_pool: concourse
    persistent_disk_pool: db

    jobs:
      - name: postgres
        release: postgres
        properties:
          databases:
            port: 5432
            databases:
              - name: atc
            roles:
              - name: atc
                password: (( grab secrets.concourse_postgres_password ))

      - name: atc
        release: concourse
        properties:
          external_url: (( concat "https://" terraform_outputs_concourse_dns_name ))
          add_local_users:
            - (( concat "admin:" secrets.concourse_atc_password ))
          auth_duration: (( grab $CONCOURSE_AUTH_DURATION ))
          main_team:
            auth:
              local:
                users:
                - admin
          postgresql:
            database: atc
            role:
              name: atc
              password: (( grab secrets.concourse_postgres_password ))
          token_signing_key: (( grab secrets.concourse_token_signing_key ))
          prometheus:
            bind_ip: 0.0.0.0
            bind_port: 9391

      - name: worker
        release: concourse
        properties:
          baggageclaim:
            url: "http://127.0.0.1:7788"
          tsa:
            host: 127.0.0.1
            port: 2222
            host_public_key: (( grab secrets.concourse_tsa_host_key.public_key ))
            worker_key: (( grab secrets.concourse_worker_key ))

      - name: tsa
        release: concourse
        properties:
          forward_host: 127.0.0.1
          atc:
            address: 127.0.0.1:8080
          host_key: (( grab secrets.concourse_tsa_host_key ))
          token_signing_key: (( grab secrets.concourse_token_signing_key ))
          authorized_keys: [(( grab secrets.concourse_worker_key.public_key ))]

      - name: baggageclaim
        release: concourse

      - name: garden
        release: garden-runc
        properties:
          garden:
            listen_network: tcp
            listen_address: 0.0.0.0:7777
            graph_cleanup_threshold_in_mb: 3072
            max_containers: 1024
            network_pool: "10.254.0.0/20"

    networks:
      - name: public
        static_ips:
        - (( grab terraform_outputs_concourse_elastic_ip ))
      - name: concourse
        static_ips: (( static_ips(0) ))
        default: [dns, gateway]

compilation:
  workers: 1
  network: concourse
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: c4.large
    availability_zone: (( grab meta.zone ))
    iam_instance_profile: compilation-vm
    auto_assign_public_ip: true

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

tags:
  deploy_env: (( grab terraform_outputs_environment ))
