---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/awscli
    tag: 895cf6752c8ec64af05a3a735186b90acd3db65a
inputs:
  - name: paas-bootstrap
run:
  path: sh
  args:
    - -e
    - -c
    - -u
    - |
      if aws s3 ls "s3://${BUCKET}/${SSH_KEY_PREFIX}id_rsa" > /dev/null; then
         aws s3 rm "s3://${BUCKET}/${SSH_KEY_PREFIX}id_rsa"
      fi
      if aws s3 ls "s3://${BUCKET}/${SSH_KEY_PREFIX}id_rsa.pub" > /dev/null; then
         aws s3 rm "s3://${BUCKET}/${SSH_KEY_PREFIX}id_rsa.pub"
      fi
      echo "Done"
