---
- type: replace
  path: /resource_pools/name=vms/stemcell
  value:
    url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-xenial-go_agent?v=621.82
    sha1: 67c691effba33dd4e55679301a80a9965640e543
