---
- type: replace
  path: /releases/name=bpm
  value:
    name: "bpm"
    version: "1.0.4"
    url: "https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=1.0.4"
    sha1: "41df19697d6a69d2552bc2c132928157fa91abe0"
