---
- type: replace
  path: /releases/name=uaa
  value:
    name: "uaa"
    version: "66.0"
    url: "https://bosh.io/d/github.com/cloudfoundry/uaa-release?v=66.0"
    sha1: "2848d9fb65d2d556a918e8045359cf469c241123"
