---
releases:
  - name: syslog
    version: 11.1.0
    url: https://bosh.io/d/github.com/cloudfoundry/syslog-release?v=11.1.0
    sha1: 0dc6bdb820584d915be548dc32c99168230b8eb3

addons:
  - name: syslog_forwarder
    jobs:
      - name: syslog_forwarder
        release: syslog
    properties:
      syslog:
        address: (( concat "logsearch-ingestor." $SYSTEM_DNS_ZONE_NAME ))
        port: 6514
        transport: 'tcp'
        tls_enabled: true
        permitted_peer: (( concat "*." $SYSTEM_DNS_ZONE_NAME ))
        custom_rule: |
          if ($programname startswith "vcap.") then ~
        use_tcp_for_file_forwarding_local_transport: true
