---

releases:
  - name: syslog
    version: 0.0.1525961026
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/syslog-0.0.1525961026.tgz
    sha1: bef1098c95684aa7cc73c170083ff9b2a98d8d22

addons:
  - name: syslog_forwarder
    jobs:
      - name: syslog_forwarder
        release: syslog
    properties:
      syslog:
        address: (( grab $LOGIT_SYSLOG_ADDRESS ))
        port: (( grab $LOGIT_SYSLOG_PORT ))
        transport: 'tcp'
        tls_enabled: true
        ca_cert: "(( grab $LOGIT_CA_CERT ))"
        client_tls:
          enabled: true
          cert: (( grab $LOGIT_CLIENT_CERT ))
          key: (( grab $LOGIT_CLIENT_KEY ))
        permitted_peer: "*.logit.io"
        custom_rule: |
          $MaxMessageSize 64k
          if ($programname startswith "vcap.") then ~
        use_tcp_for_file_forwarding_local_transport: true
