---
releases:
  - name: syslog
    version: 0.1.5
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/syslog-0.1.5.tgz
    sha1: 0c56265475bb2ddf041afddeaf85372ff06879cb

addons:
  - name: syslog_forwarder
    jobs:
      - name: syslog_forwarder
        release: syslog
    properties:
      syslog:
        address: (( grab meta.logit.syslog_address ))
        port: (( grab meta.logit.syslog_port ))
        transport: 'tcp'
        tls_enabled: true
        ca_cert: (( grab meta.logit.ca_cert ))
        permitted_peer: "*.logit.io"
        custom_rule: |
          $MaxMessageSize 64k
          if ($programname startswith "vcap.") then stop
        use_tcp_for_file_forwarding_local_transport: true
